# Streamlit Cloud Configuration
# This file helps Streamlit Cloud properly identify and deploy the app

[general]
name = "Smart Building Energy Prediction"
description = "Real-time energy consumption prediction with sustainability tracking"
version = "1.0.0"

[deployment]
url = "https://share.streamlit.io"
python_version = "3.11"
